// typegen v1 — TypeScript-compiler-API-based stub generation + native module
// compilation for the host's QuickJS engine. Implements RFC-0001 §5.
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
let ts;
try {
  ts = require("typescript");
} catch {
  ts = null; // vanilla .js apps don't need it
}

/** Extract { name, argsType, returnType, hasArgs } for each exported function. */
function analyze(entry) {
  const program = ts.createProgram([entry], {
    target: ts.ScriptTarget.ES2020,
    strict: true,
    noEmit: true,
  });
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(entry);
  const fns = [];

  source.forEachChild((node) => {
    if (!ts.isFunctionDeclaration(node) || !node.name) return;
    const exported = node.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
    if (!exported) return;

    const name = node.name.text;
    const param = node.parameters[0];
    const argsType = param?.type ? param.type.getText(source) : null;

    const sig = checker.getSignatureFromDeclaration(node);
    let ret = checker.typeToString(
      checker.getReturnTypeOfSignature(sig),
      node,
      ts.TypeFormatFlags.NoTruncation,
    );
    if (ret.startsWith("Promise<")) ret = ret.slice("Promise<".length, -1);
    fns.push({ name, argsType, returnType: ret, hasArgs: Boolean(param) });
  });
  return fns;
}

/** Emit native-client.ts with exact types (renames break the frontend at compile time). */
function emitClient(dir, fns) {
  const lines = [
    "// AUTO-GENERATED by `kestrel typegen` — do not edit.",
    "/* eslint-disable */",
    "const invoke = (name: string, args: unknown) =>",
    "  (window as any).__TAURI__.core.invoke('call_native', { name, args });",
    "",
    ...fns.map((f) =>
      f.hasArgs
        ? `export function ${f.name}(args: ${f.argsType ?? "Record<string, unknown>"}): Promise<${f.returnType}> {\n  return invoke('${f.name}', args) as Promise<${f.returnType}>;\n}`
        : `export function ${f.name}(): Promise<${f.returnType}> {\n  return invoke('${f.name}', {}) as Promise<${f.returnType}>;\n}`,
    ),
    "",
  ];
  fs.writeFileSync(path.join(dir, "native-client.ts"), lines.join("\n"));
}

/** Transpile native.ts to a script QuickJS can eval; exports land on globalThis.native. */
function compileNative(dir, entry) {
  const out = ts.transpileModule(fs.readFileSync(entry, "utf8"), {
    compilerOptions: {
      target: ts.ScriptTarget.ES2020,
      module: ts.ModuleKind.CommonJS,
    },
  }).outputText;
  const wrapped = [
    "// AUTO-GENERATED by kestrel from native.ts — do not edit.",
    "globalThis.native = globalThis.native || {};",
    "(function () {",
    "  const exports = {};",
    "  const module = { exports };",
    out,
    "  Object.assign(globalThis.native, module.exports);",
    "})();",
    "",
  ].join("\n");
  const outDir = path.join(dir, ".kestrel");
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, "native.compiled.js");
  fs.writeFileSync(outFile, wrapped);
  return outFile;
}

/** Legacy path for .js native modules (spike style: `native.fn = …`). */
function typegenJs(dir, nativePath) {
  const src = fs.readFileSync(nativePath, "utf8");
  const names = [...src.matchAll(/^\s*native\.([A-Za-z_$][\w$]*)\s*=/gm)].map((x) => x[1]);
  const js = [
    "// AUTO-GENERATED by `kestrel typegen` — do not edit.",
    "const invoke = (name, args) =>",
    "  window.__TAURI__.core.invoke('call_native', { name, args });",
    ...names.map((n) => `export const ${n} = (args = {}) => invoke('${n}', args);`),
    "",
  ].join("\n");
  fs.writeFileSync(path.join(dir, "native-client.js"), js);
  return { names, compiled: nativePath };
}

/**
 * Main entry. Returns { names, compiled } where `compiled` is the file the
 * host's QuickJS engine should load.
 */
export function runTypegen(dir, manifest) {
  if (!manifest.native) return { names: [], compiled: null };
  const entry = path.resolve(dir, manifest.native);
  if (!entry.endsWith(".ts")) return typegenJs(dir, entry);

  if (!ts)
    throw new Error(
      "native.ts requires the `typescript` package — run npm install in the kestrel repo",
    );
  const fns = analyze(entry);
  emitClient(dir, fns);
  const compiled = compileNative(dir, entry);
  return { names: fns.map((f) => f.name), compiled };
}
